# Миры, в которых действует ограничение
restricted-worlds:
  - world
  - hub
# Язык сообщения ru/eu
lang: ru

# Типы лодок, которые нельзя ставить не на воде
# Полный список всех предметов-лодок в Minecraft 1.21.10
restricted-boats:
  # Обычные лодки (Boat)
  - oak_boat
  - spruce_boat
  - birch_boat
  - jungle_boat
  - acacia_boat
  - dark_oak_boat
  - mangrove_boat
  - cherry_boat
  - bamboo_raft
  - pale_oak_boat # Добавлен в обновлении 1.21.4[citation:3]
  # Лодки с сундуком (Chest Boat)
  - oak_chest_boat
  - spruce_chest_boat
  - birch_chest_boat
  - jungle_chest_boat
  - acacia_chest_boat
  - dark_oak_chest_boat
  - mangrove_chest_boat
  - cherry_chest_boat
  - bamboo_chest_raft
  - pale_oak_chest_boat # Добавлен в обновлении 1.21.4[citation:3]


# Воспроизвести звук ошибки
play-error-sound: true
# Указать звук ошибки (Когда включено play-error-sound) - По умолчанию:
# BLOCK_ANVIL_LAND Убедитесь, что имя звука написано заглавными буквами
sound: "BLOCK_ANVIL_LAND"